### ISSUE TITLE
Disabling pylint

### ISSUE THREAD

**Issue by daltonpearson** [AtakamaLLC/lint-diffs#16]
Hi I'm trying to use this in a ci/cd pipeline and I only want to run flake8 and not pylint. I was curious if there's a better way to disable pylint than by just setting the extension=.extensionthatdoesntexist. As an aside it would also be nice to be able to set the linter options in the .lint-diffs file as well. I'm happy to make a pull requests for these features but I just wanted to double check that I'm not missing something and that you would be open to these changes.
```
# File: .lint-diffs
[pylint]
# doesn't work
enabled=false
# this works but it's a hack
extensions=.disabledthislinter

[flake8]
extensions=.py
# it would also be nice if this worked rather than having to define a seperate .flake8 file
ignore = E501,E722,F401,F841
```

**Comment by earonesty** [comment]
this should work, too... just leaving it blank

```
[pylint]
extensions=
```

i will add to the dox

**Comment by earonesty** [comment]
added
